######################################################################
# Automatically generated by qmake (2.01a) Fri Aug 20 18:01:07 2010
######################################################################

TEMPLATE = app
TARGET = ../starlight
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += BezierSpline.h Curve.h Geometry.h Mesh.h Renderable.h
SOURCES += BezierSpline.cc CoastRoll.cc Curve.cc Geometry.cc Mesh.cc

QT += opengl
